//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.DBApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int id_sale { get; set; }
        public int Product_id { get; set; }
        public int Count { get; set; }
        public decimal Cost { get; set; }
        public int Client_id { get; set; }
        public Nullable<int> Employe_id { get; set; }
        public Nullable<System.DateTime> DateSale { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}
